### ISSUE TITLE
Problem with attributes node

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#181] opened 2015-02-25 16:34 UTC
Why is in attributes node not set DataType?

**Comment by jpfr** [comment] 2015-02-25 17:10
Sorry, I didn't get that.
Do you have some more context?

**Comment by kadomcev** [comment] 2015-02-25 17:22
UaExpert -> node -> Attributes -> DataType not set	

       /* Add Folder 1 */
	UA_ObjectNode *root = UA_ObjectNode_new();
	root->nodeId = UA_NODEIDS[UA_EXPANDEDNODEID];
	root->nodeClass = UA_NODECLASS_OBJECT;
	UA_QUALIFIEDNAME_STATIC(root->browseName, "ADE7878");
	UA_LOCALIZEDTEXT_STATIC(root->displayName, "ADE7878");
	UA_LOCALIZEDTEXT_STATIC(root->description, "ADE7878");
	UA_Server_addNode(server, (const UA_Node**)&root,
					  	  	&UA_EXPANDEDNODEIDS[UA_OBJECTSFOLDER],
							&UA_NODEIDS[UA_ORGANIZES]);

	/* Add node in Folder 1 */
	UA_VariableNode *tmpNode = UA_VariableNode_new();
	UA_QualifiedName_copycstring("Ua",&tmpNode->browseName);
	UA_LocalizedText_copycstring("Ua",&tmpNode->displayName);
	UA_LocalizedText_copycstring("Int", &tmpNode->description);

	tmpNode->nodeClass = UA_NODECLASS_VARIABLE;

	tmpNode->dataType = UA_NODEIDS[UA_UINT32];  //is that correct?

	tmpNode->value.vt = &UA_TYPES[UA_INT32];
	tmpNode->value.storage.data.dataPtr = &data;
	tmpNode->value.storageType = UA_VARIANT_DATA_NODELETE;
	tmpNode->value.storage.data.arrayLength = 1;
	UA_Server_addNode(server, (const UA_Node**)&tmpNode,
					  	  	&UA_EXPANDEDNODEIDS[UA_EXPANDEDNODEID],
							&UA_NODEIDS[UA_HASCOMPONENT]);

**Comment by kadomcev** [comment] 2015-02-25 17:27
Tell me how to change the icon of the node? (change on to folder)

**Comment by jpfr** [comment] 2015-02-25 17:41
Yes. You found a bug/regression.
The objects node does not have an "organizedby" reference as it should have.
Looking into it...

**Comment by kadomcev** [comment] 2015-02-25 17:50
so what can i do?

**Comment by jpfr** [comment] 2015-02-25 20:39
@kadomcev 
Hmm. I resolved the missing references. But the folder icon is still missing.
I know that old versions of the UA Expert browse for an "Icon" node that we don't have. Don't know if they still do that.

Besides UA Expert showing the generic "object" icon, there should be no difference in functionality.
So this is WONTFIX for now.

About your original questions about attributes. Could you resolve that in the meantime?

**Comment by Stasik0** [comment] 2015-02-25 20:43
@jpfr have you got a server with a proper icon? Should we look into wireshark?

**Comment by Stasik0** [comment] 2015-02-25 21:01
@jpfr it turns out that the icon is based on "HasTypeDefinition" reference with value/or to node "FolderType", it is a shame that I do not know how to add this from userspace atm :/

**Comment by jpfr** [comment] 2015-02-25 21:16
Have a look at the current master.
We do have that reference, e.g. for the folders object. But still no icon...

**Comment by jpfr** [comment] 2015-02-25 21:18
It could be that ua expert expects a more complete objecttype hierarchy.

If you want to add your own references, use ```UA_Server_addReference``` that is visible from userspace.

**Comment by Stasik0** [comment] 2015-02-25 21:23
Something like HasSupertypeDefinition?

**Comment by Stasik0** [comment] 2015-02-25 21:44
Does not help, should we work on covering more on NS0? or just leave it?

**Comment by Stasik0** [comment] 2015-02-26 20:55
I opened a ticket http://forum.unified-automation.com/topic1473.html

**Comment by Stasik0** [comment] 2015-02-27 16:41
dang: http://forum.unified-automation.com/topic1473.html#p2635 @jpfr maybe you can run the conformance tester?

**Comment by Stasik0** [comment] 2015-02-27 18:06
Hey guys, it turns out that the browse service was the problem... ;) can you confirm @kadomcev, @jpfr?

**Comment by jpfr** [comment] 2015-02-27 18:30
Confirmed on Win/MSVC.
Great job!

**Closed by jpfr** 2015-02-27 18:30 UTC
Labels: bug

**Comment by kadomcev** [comment] 2015-02-27 19:15
Confirmed on Win)

**Comment by Stasik0** [comment] 2015-02-28 23:16
@cacamille3 thanks for your help, it was the browse service :(
