### ISSUE TITLE
Problem with ExtensionObject

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#199] opened 2015-03-06 04:35 UTC
Type ExtensionObject has field TypeId: UA_NodeId however, it should be UA_ExpandedNodeId

**Comment by kadomcev** [comment] 2015-03-06 05:30
![7](https://cloud.githubusercontent.com/assets/11058275/6520674/b1b30fa0-c3eb-11e4-9470-0a3e09011b9c.PNG)
![8](https://cloud.githubusercontent.com/assets/11058275/6520678/bdde091a-c3eb-11e4-9cc6-b7cfb1d8c16e.PNG)
![9](https://cloud.githubusercontent.com/assets/11058275/6520679/c3a6c922-c3eb-11e4-80e4-773385114837.PNG)
![10](https://cloud.githubusercontent.com/assets/11058275/6520680/c4b4c6fc-c3eb-11e4-9cf4-93450005ad09.PNG)

**Comment by kadomcev** [comment] 2015-03-06 05:31
shift two bytes

**Comment by jpfr** [comment] 2015-03-06 09:07
The standard says it needs to be a normal nodeid.
![image](https://cloud.githubusercontent.com/assets/1726411/6522722/63770538-c3e8-11e4-9079-8fc6e3f1479d.png)

That said, I actually would prefer the expandednodeid.
After all, the binary encoding is exactly the same if there is no serverindex and namespaceuri.

**Comment by kadomcev** [comment] 2015-03-06 09:16
i have to change NodeId(4 byte) in order to client read data

**Comment by kadomcev** [comment] 2015-03-06 09:17
otherwise NodeId(2 byte), client not read data(subscription)

**Comment by jpfr** [comment] 2015-03-06 09:33
That's already done internally.
We only store Int32s in the nodeid to simplify the interface. But if the identifier is small enough (and the namespace is zero), we encode it as a 2byte-nodeid or 4byte-nodeid. Decoding does the same.

**Comment by kadomcev** [comment] 2015-03-06 09:48
UaExpert -> not read PublishResponse, if NodeId has 2byte.
If NodeId has 4byte -> all fine.

**Comment by Stasik0** [comment] 2015-03-06 10:05
hmmm, what do we do?

**Comment by kadomcev** [comment] 2015-03-06 10:09
I think, that should be used NodeId with 4byte

**Comment by jpfr** [comment] 2015-03-06 10:10
What is the numeric identifier and namespace in question?

**Comment by kadomcev** [comment] 2015-03-06 10:11
You can see PublishResponse in Wireshark

**Comment by Stasik0** [comment] 2015-03-06 10:11
And reqeust?

**Comment by jpfr** [comment] 2015-03-06 10:18
@kadomcev 
In the screenshots, the nodeid identifier is also different.

The original server sends the identiier 811 (DataChangeNotification_Encoding_DefaultBinary).
You send the identifier 66 (ObjectTypeNode_Encoding_DefaultBinary).

So the difference seems to be not the encoding but the content.
NodeId(ns=0,i=66) can be encoded in 2bytes, but NodeId(ns=0,i=811) cannot.

**Comment by kadomcev** [comment] 2015-03-06 10:18
PublishResponse -> OpcUa Binary Protocol -> OpcUa Service : Encodeable Object -> TypeId : ExpandedNodeId (4bytes)

**Comment by kadomcev** [comment] 2015-03-06 10:22
when NodeId (2bytes)  NodeId =66   -> not work
when NodeId (4bytes)  NodeId =811 -> it work

**Comment by kadomcev** [comment] 2015-03-06 10:29
problem occurs when the two-byte shift

**Comment by jpfr** [comment] 2015-03-06 10:31
Ok.
Go to file ```ua_types_encoding_binary.c```.
Starting at line 290, replace the next two functions with the code below. That replaces the 2 bytes encoding with 4 bytes (or full encoding).

My guess is: The problem are not the 2 bytes. The problem is the 66 identifier.

Try and find out.

```c
size_t UA_NodeId_calcSizeBinary(UA_NodeId const *p) {
    size_t length = 0;
    switch(p->identifierType) {
    case UA_NODEIDTYPE_NUMERIC:
        if(p->identifier.numeric > UA_UINT16_MAX || p->namespaceIndex > UA_BYTE_MAX)
            length = sizeof(UA_Byte) + sizeof(UA_UInt16) + sizeof(UA_UInt32);
        else
            length = 4;  /* UA_NODEIDTYPE_FOURBYTE */
        break;
    case UA_NODEIDTYPE_STRING:
        length = sizeof(UA_Byte) + sizeof(UA_UInt16) + UA_String_calcSizeBinary(&p->identifier.string);
        break;
    case UA_NODEIDTYPE_GUID:
        length = sizeof(UA_Byte) + sizeof(UA_UInt16) + UA_Guid_calcSizeBinary(&p->identifier.guid);
        break;
    case UA_NODEIDTYPE_BYTESTRING:
        length = sizeof(UA_Byte) + sizeof(UA_UInt16) + UA_ByteString_calcSizeBinary(&p->identifier.byteString);
        break;
    default:
        UA_assert(UA_FALSE); // this must never happen
        break;
    }
    return length;
}

UA_StatusCode UA_NodeId_encodeBinary(UA_NodeId const *src, UA_ByteString * dst, size_t *offset) {
    UA_StatusCode retval = UA_STATUSCODE_GOOD;
    // temporary variables for endian-save code
    UA_Byte srcByte;
    UA_UInt16 srcUInt16;
    switch(src->identifierType) {
    case UA_NODEIDTYPE_NUMERIC:
        if(src->identifier.numeric > UA_UINT16_MAX || src->namespaceIndex > UA_BYTE_MAX) {
            srcByte = UA_NODEIDTYPE_NUMERIC;
            retval |= UA_Byte_encodeBinary(&srcByte, dst, offset);
            retval |= UA_UInt16_encodeBinary(&src->namespaceIndex, dst, offset);
            retval |= UA_UInt32_encodeBinary(&src->identifier.numeric, dst, offset);
        } else {
            srcByte = UA_NODEIDTYPE_FOURBYTE;
            retval |= UA_Byte_encodeBinary(&srcByte, dst, offset);
            srcByte = src->namespaceIndex;
            srcUInt16 = src->identifier.numeric;
            retval |= UA_Byte_encodeBinary(&srcByte, dst, offset);
            retval |= UA_UInt16_encodeBinary(&srcUInt16, dst, offset);
        }
        break;
    case UA_NODEIDTYPE_STRING:
        srcByte = UA_NODEIDTYPE_STRING;
        retval |= UA_Byte_encodeBinary(&srcByte, dst, offset);
        retval |= UA_UInt16_encodeBinary(&src->namespaceIndex, dst, offset);
        retval |= UA_String_encodeBinary(&src->identifier.string, dst, offset);
        break;
    case UA_NODEIDTYPE_GUID:
        srcByte = UA_NODEIDTYPE_GUID;
        retval |= UA_Byte_encodeBinary(&srcByte, dst, offset);
        retval |= UA_UInt16_encodeBinary(&src->namespaceIndex, dst, offset);
        retval |= UA_Guid_encodeBinary(&src->identifier.guid, dst, offset);
        break;
    case UA_NODEIDTYPE_BYTESTRING:
        srcByte = UA_NODEIDTYPE_BYTESTRING;
        retval |= UA_Byte_encodeBinary(&srcByte, dst, offset);
        retval |= UA_UInt16_encodeBinary(&src->namespaceIndex, dst, offset);
        retval |= UA_ByteString_encodeBinary(&src->identifier.byteString, dst, offset);
        break;
    default:
        UA_assert(UA_FALSE);
    }
    return retval;
}
```

**Comment by kadomcev** [comment] 2015-03-06 10:42
How then to be if NodeId is less than two bytes ?

**Comment by jpfr** [comment] 2015-03-06 10:45
Decoding is unaffected.
A NodeId never **is** less than two bytes. That's just one **possible encoding** if the identifier is small enough to fit into one byte.

**Comment by kadomcev** [comment] 2015-03-06 10:52
UA_ExtensionObject *exobj = UA_ExtensionObject_new();

        exobj->typeId.nodeId.identifier.numeric = 66;
        exobj->typeId.nodeId.identifierType = UA_NODEIDTYPE_NUMERIC;
        exobj->typeId.nodeId.namespaceIndex = 0;


must be: exobj->typeId.nodeId = MyNode.NodeId       from my server   ????

**Comment by jpfr** [comment] 2015-03-06 10:57
Since the server you tested sends an UA_DataChangeNotification structure.
That seems plausible, doesn't it?

**Comment by kadomcev** [comment] 2015-03-06 11:00
NotificationData: Array of ExtensionObject

**Comment by kadomcev** [comment] 2015-03-06 11:03
UA_ExtensionObject *exobj = UA_ExtensionObject_new();

    exobj->typeId.nodeId.identifier.numeric = 66;
    exobj->typeId.nodeId.identifierType = UA_NODEIDTYPE_NUMERIC;
    exobj->typeId.nodeId.namespaceIndex = 0;
    exobj->encoding = UA_EXTENSIONOBJECT_ENCODINGMASK_BODYISBYTESTRING;
    exobj->body = *message;

    response->notificationMessage.notificationData = exobj;
    response->notificationMessage.notificationDataSize = 1;
    response->results = status;
    response->resultsSize = 1;

**Comment by jpfr** [comment] 2015-03-06 11:06
Yes. But you can't encode whatever you like.
 > The NotificationMessage structure used in the Subscription Service set allows specifying different
types of NotificationData. The NotificationData parameter is an extensible parameter whose
structure depends on the type of Notification being sent.

Allowed are DataChangeNotification, EventNotificationList, StatusChangeNotification.

**Comment by kadomcev** [comment] 2015-03-06 11:09
as should have been done?

**Comment by kadomcev** [comment] 2015-03-06 11:11
I've done each byte as in Wireshark

**Comment by jpfr** [comment] 2015-03-06 11:24
@kadomcev 
You need to encode one of the three types I mentioned above in the extensionobject.
Where does the 66 identifier come from anyway?

```c
UA_DataChangeNotification_encodeBinary(notification, message.data, 0);
UA_ExtensionObject *exobj = UA_ExtensionObject_new();
exobj->typeId.nodeId = UA_TYPES[UA_TYPES_DATACHANGENOTIFICATION].typeId;
exobj->encoding = UA_EXTENSIONOBJECT_ENCODINGMASK_BODYISBYTESTRING;
exobj->body = *message;
```

**Comment by kadomcev** [comment] 2015-03-06 11:41
UA_DataChangeNotification_encodeBinary(notification, message.data, 0);
what's this notification?
what's this message.data?

**Comment by jpfr** [comment] 2015-03-06 12:03
We aim to provide an easy to use solution to our users.
But since subscriptions are currently not supported in open62541t, you will need *a lot* of additional information. You should get access to the standard, as we are unable to reiterate its entire content here.

I am closing this issue, since your question is no longer about extensionobject encoding.
Feel free to open a new issue under an appropriate title.

**Closed by jpfr** 2015-03-06 12:03 UTC
